# https://docs.gitlab.com/omnibus/docker/
services:

  # 
  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    hostname: '$GITLAB_HOST'
    env_file:
      ./.env
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://$GITLAB_HOST:$GITLAB_PORT';
        registry_external_url 'https://$GITLAB_REGISTRY_HOST:$GITLAB_REGISTRY_PORT';
        gitlab_rails['gitlab_shell_ssh_port'] = $GITLAB_SSH_PORT;
        letsencrypt['enable'] = false;
    ports:
      - '$GITLAB_PORT:$GITLAB_PORT'
      - '$GITLAB_REGISTRY_PORT:$GITLAB_REGISTRY_PORT'
      - '$GITLAB_SSH_PORT:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'

  # https://docs.gitlab.com/runner/install/docker.html
  gitlab-runner:
    container_name: gitlab-runner
    image: 'gitlab/gitlab-runner:latest'
    restart: unless-stopped
    env_file:
      ./.env
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '$GITLAB_RUNNER_HOME:/etc/gitlab-runner'

  # 
  redmine:
    container_name: redmine
    image: redmine
    restart: unless-stopped
    env_file:
      ./.env
    environment:
      REDMINE_DB_MYSQL: db
    ports:
      - $REDMINE_PORT:3000
    links:
      - redmine-db:db
    volumes:
      - '$REDMINE_HOME/files:/usr/src/redmine/files'
      - '$REDMINE_HOME/themes:/usr/src/redmine/public/themes'
      - '$REDMINE_HOME/plugins:/usr/src/redmine/public/plugins'

  # 
  redmine-db:
    container_name: redmine-db
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      ./.env
    environment:
      MYSQL_ROOT_PASSWORD: '$REDMINE_DB_PASSWORD'
      MYSQL_DATABASE: redmine
    volumes:
      - '$REDMINE_HOME/db:/var/lib/mysql'
